name = "TRANSLATE_MODULE"
description = "Translate text between languages"
github = "Nadybot/TRANSLATE_MODULE"
version = "1.0.6"
author = "Nadyita"
bot_type = "Nadybot"
bot_version = "^6.0.0-alpha.1"
